"""Supervised six-bot family End-expedition harness."""

from .coordinator import (
    CheckpointStore,
    ExpeditionCoordinator,
    FleetTrackerAdapter,
    build_coordinator,
    collect_readiness,
    evaluate_bot_readiness,
    prepare_expedition,
    prepare_armor,
    prepare_food_reserves,
    recover_dead_bots,
)
from .chat import (
    FamilyChatGateway,
    FamilyChatRequest,
    FamilyChatVerb,
    ServerChatMessage,
    ServerChatTailer,
    parse_family_chat,
    parse_server_chat_line,
    validate_chat_prefix,
)
from .end_sequence import (
    CrystalReservationPool,
    DragonRole,
    DragonSupportCoordinator,
    DragonSupportOutcome,
    PortalInspection,
    PortalSequence,
    assign_dragon_roles,
    inspect_portal,
    is_dragon_support_target,
)
from .escort import (
    EscortDecision,
    EscortFleet,
    EscortWorker,
    desired_position,
    formation_offsets,
    is_safe_hostile_target,
    rotate_offset,
)
from .leader_tracker import RconLeaderTracker
from .models import (
    BotReadiness,
    ExpeditionCheckpoint,
    ExpeditionConfig,
    ExpeditionPhase,
    OperatorAction,
    PlayerSnapshot,
    ReadinessReport,
    Vec3,
    validate_player_name,
)

__all__ = [
    "BotReadiness",
    "CheckpointStore",
    "CrystalReservationPool",
    "DragonRole",
    "DragonSupportCoordinator",
    "DragonSupportOutcome",
    "EscortDecision",
    "EscortFleet",
    "EscortWorker",
    "FamilyChatGateway",
    "FamilyChatRequest",
    "FamilyChatVerb",
    "ExpeditionCheckpoint",
    "ExpeditionConfig",
    "ExpeditionCoordinator",
    "ExpeditionPhase",
    "FleetTrackerAdapter",
    "OperatorAction",
    "PlayerSnapshot",
    "PortalInspection",
    "PortalSequence",
    "RconLeaderTracker",
    "ReadinessReport",
    "ServerChatMessage",
    "ServerChatTailer",
    "Vec3",
    "build_coordinator",
    "assign_dragon_roles",
    "collect_readiness",
    "evaluate_bot_readiness",
    "desired_position",
    "formation_offsets",
    "inspect_portal",
    "is_dragon_support_target",
    "is_safe_hostile_target",
    "parse_family_chat",
    "parse_server_chat_line",
    "prepare_armor",
    "prepare_expedition",
    "prepare_food_reserves",
    "recover_dead_bots",
    "rotate_offset",
    "validate_chat_prefix",
    "validate_player_name",
]
