# Gradle Properties
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_version = 1.0.29
maven_group = com.minecraftbot
archives_base_name = baritone-api-bridge

# Fabric Properties
# Check https://fabricmc.net/develop/ for latest versions
minecraft_version=26.2
loader_version=0.19.3

# Dependencies
fabric_version=0.156.0+26.2
