# Gradle Properties
org.gradle.jvmargs=-Xmx1G
# org.gradle.java.home=C:\\gh\\mcbaratone\\bridge\\jdk21\\jdk-21.0.2+13

# Mod Properties
mod_version = 1.0.21
maven_group = com.minecraftbot
archives_base_name = baritone-api-bridge

# Fabric Properties
# Check https://fabricmc.net/develop/ for latest versions
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.1

# Dependencies
fabric_version=0.141.1+1.21.11
